openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /ecosistemas:
    get:
      summary: Get Ecosistemas
      description: Optional extended description in Markdown.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EcosistemaOutDto'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    post:
      summary: Create Ecosistema
      description: Sube un ecosistema nuevo
      requestBody:
        description: Datos de ecosistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EcosistemaInDto'
      responses:
        201:
          description: Ecosistema creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response201'
  /ecosistemas/{id}:
    get:
      summary: Get Ecosistema
      description: Devuelve ecosistema por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EcosistemaDetailOutDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    put:
      summary: Update Ecosistema
      description: Devuelve y edita ecosistema por id
      requestBody:
        description: Datos de ecosistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EcosistemaInDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EcosistemaInDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    delete:
      summary: Delete Ecosistema
      description: Borra ecosistema por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
  /animales:
    get:
      summary: Get Animales
      description: Devuelve lista de animales
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnimalOutDto'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    post:
      summary: Create Animal
      description: Sube un animal nuevo
      requestBody:
        description: Datos de animal
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalInDto'
      responses:
        201:
          description: Animal creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response201'
  /animales/{id}:
    get:
      summary: Get Animal
      description: Devuelve animal por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalDetailOutDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    put:
      summary: Update Animal
      description: Devuelve y edita animal por id
      requestBody:
        description: Datos de animal
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalInDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    delete:
      summary: Delete Animal
      description: Borra animal por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
  /usuarios:
    get:
      summary: Get Usuarios
      description: Devuelve lista de usuarios
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsuarioOutDto'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    post:
      summary: Create Usuario
      description: Sube un usuario nuevo
      requestBody:
        description: Datos de usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInDto'
      responses:
        201:
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response201'
  /usuarios/{id}:
    get:
      summary: Get Usuario
      description: Devuelve usuario por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioDetailOutDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    put:
      summary: Update Usuario
      description: Devuelve y edita usuario por id
      requestBody:
        description: Datos de usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    delete:
      summary: Delete Usuario
      description: Borra usuario por id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
components:
  schemas:
    Ecosistema:
      type: object
      properties:
        id:
          type: long
          description: identificador de ecosistema
        nombre:
          type: string
          description: nombre del ecosistema
        descripcion:
          type: string
          description: Descripci贸n del ecosistema
        temperaturaMedia:
          type: float
          description: Temperatura media registrada en el ecosistema
        active:
          type: boolean
          description: Est谩 permitido apadrinar de aqui
        createdAt:
          type: date
          format: "date-time"
          description: fecha donde el ecosistema fue dado de alta
    EcosistemaDetailOutDto:
      type: object
      properties:
        id:
          description: identificador de ecosistema
          type: long
        nombre:
          type: string
          description: nombre del ecosistema
        descripcion:
          type: string
          description: Descripci贸n del ecosistema
        temperaturaMedia:
          type: float
          description: Temperatura media registrada en el ecosistema
        animales:
          type: List
          description: lista de animales pertenecientes a ese ecosistema
        active:
          type: boolean
          description: Est谩 permitido apadrinar de aqui
        createdAt:
          type: date
          format: "date-time"
          description: fecha donde el ecosistema fue dado de alta
    EcosistemaInDto:
      type: object
      required: [nombre, descripcion, temperaturaMedia, active createdAt]
      properties:
        nombre:
          type: string
          description: nombre del ecosistema
        descripcion:
          type: string
          description: Descripci贸n del ecosistema
        temperaturaMedia:
          type: float
          description: Temperatura media registrada en el ecosistema
        active:
          type: boolean
          description: Est谩 permitido apadrinar de aqui
        createdAt:
          type: date
          format: "date-time"
          description: fecha donde el ecosistema fue dado de alta
    EcosistemaOutDto:
      type: object
      properties:
        id:
          type: long
          description: identificador de ecosistema
        nombre:
          type: string
          description: nombre del ecosistema
        descripcion:
          type: string
          description: Descripci贸n del ecosistema
    Animal:
      type: object
      properties:
        id:
          type: long
          description: identificador de animal
        nombre:
          type: string
          description: nombre del animal
        especie:
          type: string
          description: Especie del animal
        peso:
          type: float
          description: Temperatura media registrada en el animal
        EnPeligro:
          type: boolean
          description: Est谩 en peligro
        fechaAvistamiento:
          type: date
          format: "date-time"
          description: fecha donde el animal fue avistado por primera vez
        apadrinado:
          type: boolean
          description: si el animal est谩 apadrinado o no
        ecosistema:
          type: object
          description: ecosistema donde vive el animal
        usuarios:
          type: array
          description: lista de usuarios que apadrinan al mismo animal
    AnimalDetailOutDto:
      type: object
      properties:
        id:
          description: identificador de animal
          type: long
        nombre:
          type: string
          description: nombre del animal
        especie:
          type: string
          description: Especie del animal
        peso:
          type: float
          description: Temperatura media registrada en el animal
        EnPeligro:
          type: boolean
          description: Est谩 en peligro
        EcosistemaOutDto:
          type: object
          description: Ecosistema que pertenece
        UsuarioOutDto:
          type: object
          description: Usuario que lo apadrin贸
        fechaAvistamiento:
          type: date
          format: "date-time"
          description: fecha donde el animal fue avistado por primera vez
    AnimalInDto:
      type: object
      required: [nombre, descripcion, temperaturaMedia, active createdAt]
      properties:
        nombre:
          type: string
          description: nombre del animal
        especie:
          type: string
          description: Especie del animal
        peso:
          type: float
          description: Temperatura media registrada en el animal
        EnPeligro:
          type: boolean
          description: Est谩 en peligro
        fechaAvistamiento:
          type: date
          format: "date-time"
          description: fecha donde el animal fue avistado por primera vez
        apadrinado:
          type: boolean
          description: si el animal est谩 apadrinado o no
    AnimalOutDto:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del animal
        especie:
          type: string
          description: Especie del animal
        peso:
          type: float
          description: Temperatura media registrada en el animal
        apadrinado:
          type: boolean
          description: si el animal est谩 apadrinado o no
    Usuario:
      type: object
      properties:
        id:
          type: long
          description: identificador de usuario
        nombre:
          type: string
          description: nombre del usuario
        apellidos:
          type: string
          description: Apellidos del usuario
        dni:
          type: string
          description: Dni del usuario
        email:
          type: string
          format: email
          description: email de usuario
        colaborador:
          type: boolean
          description: ha colaborado antes con nosotros
        fechaNacimiento:
          type: 'date-time'
          description: fecha de nacimiento del usuario
        intencionesApadrinar:
          type: integer
          description: n煤mero de animales que tiene intenci贸n de apadrinar
        animales:
          type: array
          description: animales apadrinados por el usuario
    UsuarioDetailOutDto:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del usuario
        apellidos:
          type: string
          description: Apellidos del usuario
        dni:
          type: string
          description: Dni del usuario
        email:
          type: string
          description: email del usuario
        fechaNacimiento:
          type: 'date-time'
          description: fecha de nacimiento del usuario
        intencionesApadrinar:
          type: integer
          description: n煤mero de animales que tiene intenci贸n de apadrinar
        colaborador:
          type: boolean
          description: ha colaborado antes con nosotros
    UsuarioInDto:
      type: object
      required: [nombre, apellidos, dni, email, fechaNacimiento, intencionesApadrinar, colaborador]
      properties:
        nombre:
          type: string
          description: nombre del usuario
        apellidos:
          type: string
          description: Apellidos del usuario
        dni:
          type: string
          description: Dni del usuario
        email:
          type: string
          description: email del usuario
        fechaNacimiento:
          type: 'date-time'
          description: fecha de nacimiento del usuario
        intencionesApadrinar:
          type: integer
          description: n煤mero de animales que tiene intenci贸n de apadrinar
        colaborador:
          type: boolean
          description: ha colaborado antes con nosotros
    UsuarioOutDto:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del usuario
        apellidos:
          type: string
          description: Apellidos del usuario
        dni:
          type: string
          description: Dni del usuario
        email:
          type: string
          description: email del usuario
    ErrorResponse:
      type: object
      properties:
        code:
          type: numbre
          format: int
          description: c贸digo de estado
        title:
          type: string
          description: t铆tulo
        message:
          type: string
          description: body mesage
    Error404:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 404
        title: Not Found
        message: Resource Not Found
    Response200:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 200
        title: Ok
        message: 隆Se complet贸 con 茅xito!サ
    Response201:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 201
        title: Created
        message: 隆Se complet贸 con 茅xito!
    Error500:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 500
        title: InternalError
        message: Internal Server Error